### ISSUE TITLE
NodeFinder Enhancement.

### ISSUE THREAD

**Issue by TenshiLyle** [CodingAvenue/ca-school-proof-library#13]
From https://github.com/CodingAvenue/ca-school-proof-library/pull/10#issuecomment-290626555

```php
$code->find('++$var')->count();

// or

$code->find('$var:increment')->count();
```

**Comment by TenshiLyle** [comment]
The `count()` can be easily implemented.

The `find()` will be a challenge. We will be have to do string parsing.

I would also highly recommend to let the authors pass the nodes ( parsed by the Php Parser ) to the method. This is because authors might need to further test the result from the other tests.

E.g.  Create a function `sayHi()` that accepts a string and return a string that appends "Hi" to the parameter passed.

The author would most likely search first for a function with a name `sayHi`. Then the result will then be used to test if it contains a variable interpolation operator and a return construct. Something like this on my current implementation

```php
 $nodes = $code->parser()->getNodes();
 $finder = new NodeFinder();

 $functionNodes = $finder->findFunction($nodes, ['name' => 'sayHi']);
 $this->assertEqual(1, count($functionNodes), "sayHi function is created");

 $returnNodes = $finder->findConstruct($functionNodes, ['name' => 'return']);
 $interpolate = $finder->findEncapsed($returnNodes);
 $this->assertEqual(1, count($interpolate), "Variable Interpolation used on the return statement");

 $stringEncapsed = $finder->findEncapsedString($returnNodes);
 $this->assertEqual('Hi', $stringEncapsed->value, "a string Hi is used on the return string");
```

**Comment by TenshiLyle** [comment]
@sandaemc @tbasilio @nlabrador

**Comment by sandaemc** [comment]
In traversal, I was thinking in the line of, 

Example:

```php
$func = $code->find('function:sayHi'); // return node
$return = $func->find('statement:return'); // return node
$return->text(); // return the value being returned

// or

$code->find('function:sayHi > statement:return')->text();
```

This resembles, CSS selector/query. This way users can easily traverse to find what it need. This is also expressive, so proof writers are happy to maintain this stuff.

**Comment by sandaemc** [comment]
It's an example, I feel there could be more like:

```php
$code->find('statement[name="echo"]:first')->text();
```

**Comment by TenshiLyle** [comment]
I like it, will work on this one.
