### ISSUE TITLE
code sniffer new line character

### ISSUE THREAD

**Issue by TenshiLyle** [CodingAvenue/ca-school-proof-library#22]
When running the code sniffer for PSR2 standard check on windows, we're getting this one
```
not ok 6 - Failure: AssignAmericanToCitizenshipTest::testCodingStandard
 ---
 message: 'Coding Standard Violations found - End of line character is invalid; expected "\n" but found "\r\n" on Line 1 Column 1, '
 severity: fail
 data:
     got: 'End of line character is invalid; expected "\n" but found "\r\n" on Line 1 Column 1, '
     expected: ''
 ...
```

I think we can ignore this message.

**Comment by TenshiLyle** [comment]
@sandaemc @tbasilio thoughts?

**Comment by sandaemc** [comment]
Does Git on Windows configured to checkout in Linux or Windows line-ending style?

We could probably create a rule to ignore line-ending. It doesn't matter.

**Comment by TenshiLyle** [comment]
> Does Git on Windows configured to checkout in Linux or Windows line-ending style?

I'm not sure I understand?

**Comment by sandaemc** [comment]
During installation of Git on Windows it asks for your line-ending style for cloning or checking out a branch. I assume it converts Linux line-ending to Windows line-ending `\r\n` because it's the default.

Anyone, I think we can ignore this rule because the user can't even determine it from our REPL.

**Comment by TenshiLyle** [comment]
This was fix on https://github.com/CodingAvenue/ca-school-proof-library/commit/8c9889f996a7be8c269035c4439321e8ae5658b1
