### ISSUE TITLE
Configuration enhancement

### ISSUE THREAD

**Issue by TenshiLyle** [CodingAvenue/ca-school-proof-library#24]
We need to read the configuration `proof.json` file even on the sandbox environment ( no `PROOF_LIBRARY_MODE` env ). But we need to ignore some of them if we're inside the sandbox, namely

 - answerDir
 - testDir
 - codeFilePath

Then we need another configuration, `disableCodingConvention` and `disableMessDetection`, both are default to false. When true, The analyzer class methods for `Coding Standard` and `Mess Detection` should always return an empty array(), to mimic a success.

**Comment by TenshiLyle** [comment]
@sandaemc FYI

**Comment by sandaemc** [comment]
I think `suppressCodingConventionErrors` and `suppressMessDetectionErrors` might be more self-explanatory.
