### ISSUE TITLE
evaluate user code

### ISSUE THREAD

**Issue by TenshiLyle** [CodingAvenue/ca-school-proof-library#5]
I'm still not sure how to implement this one. Are we going to `eval` the user code?

**Comment by TenshiLyle** [comment]
@sandaemc @tbasilio thoughts?

**Comment by sandaemc** [comment]
I think it will eval like a REPL?

**Comment by tbasilio** [comment]
Suppose a student writes a function and we need to verify whether or not a factorial is correctly implemented. First we do a syntax check and then we evaluate the code. The tests run the code and look for expected returns.
